# Notebook smoke test
#
# Tests whether the notebook runs.

name: tests

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install apt dependencies
      run: xargs -a .binder/apt.txt sudo apt-get install

    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}_conda_${{ hashFiles('.binder/environment.yml') }}

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: ".binder/environment.yml"
        python-version: 3.7

    - name: System information
      run: python .github/workflows/system_info.py

    - name: Get pip cache dir
      id: pip-cache
      run: echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest nbsmoke

    - name: Debug environment
      run: |
        echo "which conda:"
        which conda
        echo "conda info:"
        conda info -a  || echo "No conda"
        echo "conda env export:"
        conda env export | cat || echo "No conda"
        echo "which python:"
        which python
        echo "python version:"
        python --version
        echo "pip freeze:"
        python -m pip freeze

    - name: "Lint check"
      run: python -m pytest --nbsmoke-lint .

    - name: "Smoke test"
      run: python -m pytest --nbsmoke-run .
